"""Remove CurrentContext

Revision ID: 0a19ea923200
Revises: 1ed3943555d7
Create Date: 2026-08-07 03:13:27.829152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a19ea923200'
down_revision: Union[str, Sequence[str], None] = '1ed3943555d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('current_context')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('current_context',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('context_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['context_id'], ['context.id'], name=op.f('fk_current_context_context_id_context')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_current_context'))
    )
    # ### end Alembic commands ###
