"""add ArchivedLink content status and embedding

Revision ID: 14ecc7c9255a
Revises: b13920e423df
Create Date: 2026-08-17 00:20:05.104785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14ecc7c9255a'
down_revision: Union[str, Sequence[str], None] = 'b13920e423df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema, then locally embed title+reason for every existing row (no network
    calls -- content embedding is a separate, on-demand step, see `kb ab backfill-content`)."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archived_link', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'content_status',
                sa.Enum('NOT_ATTEMPTED', 'EMBEDDED', 'FETCH_FAILED', name='archivedlinkcontentstatus', create_constraint=True),
                nullable=False,
                server_default='NOT_ATTEMPTED',
            )
        )
        batch_op.add_column(sa.Column('content_fetch_error', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('embedding_model', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('embedding', sa.Text(), nullable=True))

    # ### end Alembic commands ###

    from sqlalchemy.orm import Session

    from models import ArchivedLink

    bind = op.get_bind()
    with Session(bind=bind) as session:
        for link in session.scalars(sa.select(ArchivedLink)).all():
            link.reembed()
        session.commit()


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archived_link', schema=None) as batch_op:
        batch_op.drop_column('embedding')
        batch_op.drop_column('embedding_model')
        batch_op.drop_column('content_fetch_error')
        batch_op.drop_column('content_status')

    # ### end Alembic commands ###
