"""add unique constraint on archived_link.url

Revision ID: 1e4e7b4a90bd
Revises: 757a3b4ecc46
Create Date: 2026-08-12 15:00:15.668570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e4e7b4a90bd'
down_revision: Union[str, Sequence[str], None] = '757a3b4ecc46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archived_link', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_archived_link_url'), ['url'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archived_link', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_archived_link_url'), type_='unique')

    # ### end Alembic commands ###
