"""add unique constraint on instruction title

Revision ID: 1ed3943555d7
Revises: 8a475ed239f4
Create Date: 2026-08-06 14:48:15.535120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ed3943555d7'
down_revision: Union[str, Sequence[str], None] = '8a475ed239f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instruction', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_instruction_title'), ['title'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instruction', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_instruction_title'), type_='unique')

    # ### end Alembic commands ###
