"""add wishlist pinned flag

Revision ID: 244479b916a4
Revises: 4487f9c364cd
Create Date: 2026-07-07 14:50:07.601239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '244479b916a4'
down_revision: Union[str, Sequence[str], None] = '4487f9c364cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pinned', sa.Boolean(), nullable=False, server_default=sa.false()))

    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.alter_column('pinned', server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.drop_column('pinned')

    # ### end Alembic commands ###
