"""add HarnessSession.listener_pid for self-healing stale is_listening

Revision ID: 2d9f1c0ff978
Revises: 14ecc7c9255a
Create Date: 2026-08-17 01:24:48.508534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d9f1c0ff978'
down_revision: Union[str, Sequence[str], None] = '14ecc7c9255a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('harness_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('listener_pid', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('harness_session', schema=None) as batch_op:
        batch_op.drop_column('listener_pid')

    # ### end Alembic commands ###
