"""Add semantic search embeddings to Item, Vendor, Purchase

Revision ID: 3c369ac92767
Revises: 2d9f1c0ff978
Create Date: 2026-08-17 16:19:57.956344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c369ac92767'
down_revision: Union[str, Sequence[str], None] = '2d9f1c0ff978'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding_model', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('embedding', sa.Text(), nullable=True))

    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding_model', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('embedding', sa.Text(), nullable=True))

    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding_model', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('embedding', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.drop_column('embedding')
        batch_op.drop_column('embedding_model')

    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.drop_column('embedding')
        batch_op.drop_column('embedding_model')

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('embedding')
        batch_op.drop_column('embedding_model')

    # ### end Alembic commands ###
