"""Add severity to Todo

Revision ID: 3e17c8e7e501
Revises: cdc697bc3d33
Create Date: 2026-08-27 13:49:24.044281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e17c8e7e501'
down_revision: Union[str, Sequence[str], None] = 'cdc697bc3d33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('severity', sa.Enum('CRITICAL', 'MAJOR', 'MINOR', name='todoseverity', create_constraint=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_column('severity')

    # ### end Alembic commands ###
