"""add category to inbox_item

Revision ID: 3e3b68c41098
Revises: 7b72b6cfb914
Create Date: 2026-07-03 20:29:09.208437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e3b68c41098'
down_revision: Union[str, Sequence[str], None] = '7b72b6cfb914'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inbox_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inbox_item', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
