"""add Daily.show_after_hour

Revision ID: 4487f9c364cd
Revises: cfa3008307d1
Create Date: 2026-07-07 11:46:26.634759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4487f9c364cd'
down_revision: Union[str, Sequence[str], None] = 'cfa3008307d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_after_hour', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily', schema=None) as batch_op:
        batch_op.drop_column('show_after_hour')

    # ### end Alembic commands ###
