"""add Settings table, Daily domain/tier/last_completed_at

Revision ID: 4d58bd25930e
Revises: ebdcaff2e117
Create Date: 2026-07-05 16:50:53.343933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d58bd25930e'
down_revision: Union[str, Sequence[str], None] = 'ebdcaff2e117'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_boundary_hour', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settings'))
    )
    with op.batch_alter_table('daily', schema=None) as batch_op:
        batch_op.add_column(sa.Column('domain', sa.String(), nullable=False, server_default='irl'))
        batch_op.add_column(sa.Column('tier', sa.Enum('CRITICAL', 'OPTIONAL', name='dailytier', create_constraint=True), nullable=False, server_default='CRITICAL'))
        batch_op.add_column(sa.Column('last_completed_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily', schema=None) as batch_op:
        batch_op.drop_column('last_completed_at')
        batch_op.drop_column('tier')
        batch_op.drop_column('domain')

    op.drop_table('settings')
    # ### end Alembic commands ###
