"""drop instruction.parent_id (migrated to EntityLink parent-of)

Revision ID: 5187fdbc0a5e
Revises: da1fb439f9e5
Create Date: 2026-08-15 02:23:00.468085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5187fdbc0a5e'
down_revision: Union[str, Sequence[str], None] = 'da1fb439f9e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Drop parent_id -- must only run after its data has been backfilled into EntityLink
    "parent-of" rows (see kb Todo #127; done by hand for the existing DB before this
    migration was generated, since it's a one-time data move, not schema-expressible)."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instruction', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_instruction_parent_id_instruction'), type_='foreignkey')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instruction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_instruction_parent_id_instruction'), 'instruction', ['parent_id'], ['id'])

    # ### end Alembic commands ###
