"""add instruction_root_id to settings

Revision ID: 51ab34d0c302
Revises: 8139e7aaf009
Create Date: 2026-08-06 02:37:47.827415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51ab34d0c302'
down_revision: Union[str, Sequence[str], None] = '8139e7aaf009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instruction_root_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_settings_instruction_root_id_instruction'), 'instruction', ['instruction_root_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_settings_instruction_root_id_instruction'), type_='foreignkey')
        batch_op.drop_column('instruction_root_id')

    # ### end Alembic commands ###
