"""add deleted_at to Base and hard_delete_enabled to Settings

Revision ID: 593956f80f94
Revises: fb1c031e54e8
Create Date: 2026-09-16 19:43:03.442428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '593956f80f94'
down_revision: Union[str, Sequence[str], None] = 'fb1c031e54e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archived_link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('changelog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('channel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('channel_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('channel_read', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('channel_subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('cli_invocation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('context', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('context_tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('daily', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('entity_link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('harness_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('idea', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('inbox_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('instruction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('journal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('log_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('pg_character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('pg_dungeon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('pg_hangout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('pg_hangout_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('pg_mob', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('pg_mob_drop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('pg_npc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('pg_npc_race', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('pg_npc_relation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('pg_player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('pg_quest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('pg_skill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('reference', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('hard_delete_enabled', sa.Boolean(), nullable=False, server_default=sa.true())
        )
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('timer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('transcript_cache', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('usage_sample', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('vendor_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('working_memory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('working_memory', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('vendor_item', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('usage_sample', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('transcript_cache', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('timer', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('hard_delete_enabled')

    with op.batch_alter_table('reference', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('pg_skill', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('pg_quest', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('pg_player', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('pg_npc_relation', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('pg_npc_race', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('pg_npc', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('pg_mob_drop', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('pg_mob', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('pg_hangout_item', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('pg_hangout', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('pg_dungeon', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('pg_character', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('log_entry', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('journal', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('instruction', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('inbox_item', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('idea', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('harness_session', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('entity_link', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('daily', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('context_tag', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('context', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('cli_invocation', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('channel_subscription', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('channel_read', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('channel_message', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('channel', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('changelog', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('archived_link', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
