"""Add notifications_muted and notifications_volume to Settings

Revision ID: 6c6bfdd84138
Revises: 93124937e750
Create Date: 2026-07-27 03:19:17.555747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c6bfdd84138'
down_revision: Union[str, Sequence[str], None] = '93124937e750'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notifications_muted', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('notifications_volume', sa.Integer(), nullable=False, server_default='100'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('notifications_volume')
        batch_op.drop_column('notifications_muted')

    # ### end Alembic commands ###
