"""Add ArchivedLink.push_status and resolved_at

Revision ID: 757a3b4ecc46
Revises: f82f6e6c5810
Create Date: 2026-08-11 21:06:40.729838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '757a3b4ecc46'
down_revision: Union[str, Sequence[str], None] = 'f82f6e6c5810'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archived_link', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'push_status',
                sa.Enum('PENDING', 'QUEUED', 'SUCCESS', 'FAILED', name='archivedlinkpushstatus', create_constraint=True),
                nullable=False,
                server_default='PENDING',
            )
        )
        batch_op.add_column(sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archived_link', schema=None) as batch_op:
        batch_op.drop_column('resolved_at')
        batch_op.drop_column('push_status')

    # ### end Alembic commands ###
