"""replace session_message/session_message_read with Channel-based messaging

Revision ID: 7f62587f429d
Revises: ac625a09fecd
Create Date: 2026-08-22 00:44:48.681712

"""
from datetime import datetime, timezone
from typing import Any, Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f62587f429d'
down_revision: Union[str, Sequence[str], None] = 'ac625a09fecd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Self-healing against a partial prior run: SQLite DDL isn't transactional, so a crash
    # mid-migration (e.g. the data-migration step) can leave these new tables created but
    # empty/un-stamped by Alembic. Drop them unconditionally before recreating so this
    # migration is safely re-runnable from scratch without any manual sqlite3 intervention.
    # Order respects FK dependencies (read/message/subscription reference channel; message is
    # also referenced by read).
    op.execute("DROP TABLE IF EXISTS channel_read")
    op.execute("DROP TABLE IF EXISTS channel_message")
    op.execute("DROP TABLE IF EXISTS channel_subscription")
    op.execute("DROP TABLE IF EXISTS channel")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel')),
    sa.UniqueConstraint('name', name=op.f('uq_channel_name'))
    )
    op.create_table('channel_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('from_session', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], name=op.f('fk_channel_message_channel_id_channel')),
    sa.ForeignKeyConstraint(['from_session'], ['harness_session.id'], name=op.f('fk_channel_message_from_session_harness_session')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_message'))
    )
    op.create_table('channel_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('subscribed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], name=op.f('fk_channel_subscription_channel_id_channel')),
    sa.ForeignKeyConstraint(['session_id'], ['harness_session.id'], name=op.f('fk_channel_subscription_session_id_harness_session')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_subscription')),
    sa.UniqueConstraint('channel_id', 'session_id', name='uq_channel_subscription')
    )
    op.create_table('channel_read',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('up_to_message_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], name=op.f('fk_channel_read_channel_id_channel')),
    sa.ForeignKeyConstraint(['session_id'], ['harness_session.id'], name=op.f('fk_channel_read_session_id_harness_session')),
    sa.ForeignKeyConstraint(['up_to_message_id'], ['channel_message.id'], name=op.f('fk_channel_read_up_to_message_id_channel_message')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_read'))
    )
    _migrate_data()

    op.drop_table('session_message_read')
    op.drop_table('session_message')
    # ### end Alembic commands ###


def _migrate_data() -> None:
    """Moves every existing session_message/session_message_read row into the new
    Channel/ChannelMessage/ChannelSubscription/ChannelRead shape -- run once, right after the
    new tables are created and before the old ones are dropped, so no history is lost. Each
    distinct (from_session, to_session) DM pair collapses into one nameless 2-subscriber
    channel (subscribed_at backdated to that pair's earliest message, so unread()'s
    subscribed_at bound never hides a migrated message); every is_broadcast row becomes a
    message in one newly created "broadcast" channel, with every then-live-at-migration-time
    HarnessSession subscribed to it (matches cmd_register's new auto-subscribe-at-registration
    behavior, applied retroactively to existing sessions rather than left unsubscribed).
    session_message_read rows become ChannelRead rows, one per (message, session) pair, each
    pinned to up_to_message_id = that migrated message's own new id (a faithful "as of this
    read, this message was seen" -- not a true historical max like new rows will have, since
    the old per-message read-receipt model didn't record a channel-wide cursor, but the closest
    honest value obtainable from what was actually stored)."""
    conn = op.get_bind()

    old_messages = conn.execute(
        sa.text(
            "SELECT id, from_session, to_session, is_broadcast, body, created_at, updated_at "
            "FROM session_message ORDER BY id"
        )
    ).fetchall()
    old_reads = conn.execute(
        sa.text("SELECT id, message_id, session_id, created_at FROM session_message_read")
    ).fetchall()

    channel_table = sa.table(
        "channel",
        sa.column("id", sa.Integer),
        sa.column("name", sa.String),
        sa.column("created_at", sa.DateTime),
        sa.column("updated_at", sa.DateTime),
    )
    sub_table = sa.table(
        "channel_subscription",
        sa.column("id", sa.Integer),
        sa.column("channel_id", sa.Integer),
        sa.column("session_id", sa.String),
        sa.column("subscribed_at", sa.DateTime),
        sa.column("created_at", sa.DateTime),
        sa.column("updated_at", sa.DateTime),
    )
    msg_table = sa.table(
        "channel_message",
        sa.column("id", sa.Integer),
        sa.column("channel_id", sa.Integer),
        sa.column("from_session", sa.String),
        sa.column("body", sa.Text),
        sa.column("created_at", sa.DateTime),
        sa.column("updated_at", sa.DateTime),
    )
    read_table = sa.table(
        "channel_read",
        sa.column("id", sa.Integer),
        sa.column("channel_id", sa.Integer),
        sa.column("session_id", sa.String),
        sa.column("read_at", sa.DateTime),
        sa.column("up_to_message_id", sa.Integer),
        sa.column("created_at", sa.DateTime),
        sa.column("updated_at", sa.DateTime),
    )

    def _insert_returning_id(table: sa.TableClause, **values: Any) -> int:
        conn.execute(sa.insert(table).values(**values))
        new_id = conn.execute(sa.text("SELECT last_insert_rowid()")).scalar_one()
        assert isinstance(new_id, int)
        return new_id

    def _parse_dt(value: Union[datetime, str]) -> datetime:
        """Raw sa.text() SELECTs return SQLite DATETIME columns as plain strings, not
        parsed Python datetimes -- unlike ORM-mapped reads, which go through the DateTime
        type's result processor. Every timestamp pulled from old_messages/old_reads below
        must be parsed before it's used as a value for a typed DateTime insert column."""
        if isinstance(value, datetime):
            return value
        return datetime.fromisoformat(value)

    now = datetime.now(timezone.utc)

    dm_channel_by_pair: dict[tuple[str, str], int] = {}
    broadcast_channel_id: int | None = None
    old_id_to_new_msg_id: dict[int, int] = {}

    for row in old_messages:
        row_created_at = _parse_dt(row.created_at)
        row_updated_at = _parse_dt(row.updated_at)
        if row.is_broadcast:
            if broadcast_channel_id is None:
                broadcast_channel_id = _insert_returning_id(
                    channel_table, name="broadcast", created_at=now, updated_at=now
                )
                live_sessions = conn.execute(sa.text("SELECT id FROM harness_session")).fetchall()
                for live_row in live_sessions:
                    conn.execute(
                        sa.insert(sub_table).values(
                            channel_id=broadcast_channel_id,
                            session_id=live_row.id,
                            subscribed_at=row_created_at,
                            created_at=now,
                            updated_at=now,
                        )
                    )
            assert broadcast_channel_id is not None
            channel_id = broadcast_channel_id
        else:
            pair = (row.from_session, row.to_session) if row.from_session <= row.to_session else (
                row.to_session,
                row.from_session,
            )
            dm_channel_id = dm_channel_by_pair.get(pair)
            if dm_channel_id is None:
                dm_channel_id = _insert_returning_id(channel_table, name=None, created_at=now, updated_at=now)
                dm_channel_by_pair[pair] = dm_channel_id
                # dict.fromkeys dedupes while preserving order, needed because a
                # self-message (from_session == to_session, e.g. a session messaging
                # itself) would otherwise insert the same (channel_id, session_id)
                # subscription twice and violate the unique constraint.
                for session_id in dict.fromkeys((row.from_session, row.to_session)):
                    conn.execute(
                        sa.insert(sub_table).values(
                            channel_id=dm_channel_id,
                            session_id=session_id,
                            subscribed_at=row_created_at,
                            created_at=now,
                            updated_at=now,
                        )
                    )
            channel_id = dm_channel_id

        new_msg_id = _insert_returning_id(
            msg_table,
            channel_id=channel_id,
            from_session=row.from_session,
            body=row.body,
            created_at=row_created_at,
            updated_at=row_updated_at,
        )
        old_id_to_new_msg_id[row.id] = new_msg_id

    for row in old_reads:
        migrated_msg_id = old_id_to_new_msg_id.get(row.message_id)
        if migrated_msg_id is None:
            continue
        new_channel_id = conn.execute(
            sa.select(msg_table.c.channel_id).where(msg_table.c.id == migrated_msg_id)
        ).scalar_one()
        conn.execute(
            sa.insert(read_table).values(
                channel_id=new_channel_id,
                session_id=row.session_id,
                read_at=_parse_dt(row.created_at),
                up_to_message_id=migrated_msg_id,
                created_at=now,
                updated_at=now,
            )
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_message',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('from_session', sa.VARCHAR(), nullable=False),
    sa.Column('to_session', sa.VARCHAR(), nullable=True),
    sa.Column('body', sa.TEXT(), nullable=False),
    sa.Column('read_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('is_broadcast', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False),
    sa.ForeignKeyConstraint(['from_session'], ['harness_session.id'], name=op.f('fk_session_message_from_session_harness_session')),
    sa.ForeignKeyConstraint(['to_session'], ['harness_session.id'], name=op.f('fk_session_message_to_session_harness_session')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_message'))
    )
    op.create_table('session_message_read',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('message_id', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['session_message.id'], name=op.f('fk_session_message_read_message_id_session_message')),
    sa.ForeignKeyConstraint(['session_id'], ['harness_session.id'], name=op.f('fk_session_message_read_session_id_harness_session')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_message_read')),
    sa.UniqueConstraint('message_id', 'session_id', name=op.f('uq_session_message_read'))
    )
    op.drop_table('channel_read')
    op.drop_table('channel_subscription')
    op.drop_table('channel_message')
    op.drop_table('channel')
    # ### end Alembic commands ###
