"""add timer table

Revision ID: 80f5d7e6315a
Revises: ab1019a26d33
Create Date: 2026-07-13 23:15:03.232250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80f5d7e6315a'
down_revision: Union[str, Sequence[str], None] = 'ab1019a26d33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'COMPLETED', 'CANCELLED', name='timerstatus', create_constraint=True), nullable=False),
    sa.Column('repeat_count', sa.Integer(), nullable=True),
    sa.Column('completed_runs', sa.Integer(), nullable=False),
    sa.Column('context_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['context_id'], ['context.id'], name=op.f('fk_timer_context_id_context')),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name=op.f('fk_timer_tag_id_tag')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timer'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timer')
    # ### end Alembic commands ###
