"""Add urgent flag to Todo

Revision ID: 8139e7aaf009
Revises: c279a025c90b
Create Date: 2026-08-01 03:24:22.470160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8139e7aaf009'
down_revision: Union[str, Sequence[str], None] = 'c279a025c90b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('urgent', sa.Boolean(), nullable=False, server_default=sa.false()))

    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.alter_column('urgent', server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_column('urgent')

    # ### end Alembic commands ###
