"""remove instruction_root_id from settings

Revision ID: 8a475ed239f4
Revises: 51ab34d0c302
Create Date: 2026-08-06 13:28:03.206162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a475ed239f4'
down_revision: Union[str, Sequence[str], None] = '51ab34d0c302'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_settings_instruction_root_id_instruction'), type_='foreignkey')
        batch_op.drop_column('instruction_root_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instruction_root_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_settings_instruction_root_id_instruction'), 'instruction', ['instruction_root_id'], ['id'])

    # ### end Alembic commands ###
