"""add Daily, Item, PgItem, CurrentContext

Revision ID: 8c70d52bf981
Revises: fb67de424aa1
Create Date: 2026-07-01 22:33:49.918246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c70d52bf981'
down_revision: Union[str, Sequence[str], None] = 'fb67de424aa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('current_context',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('context_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['context_id'], ['context.id'], name=op.f('fk_current_context_context_id_context')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_current_context'))
    )
    op.create_table('daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('context_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('reward', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['context_id'], ['context.id'], name=op.f('fk_daily_context_id_context')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily'))
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('context_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['context_id'], ['context.id'], name=op.f('fk_item_context_id_context')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_item'))
    )
    op.create_table('pg_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('sources', sa.Text(), nullable=True),
    sa.Column('max_stack_size', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['item.id'], name=op.f('fk_pg_item_id_item')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pg_item'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pg_item')
    op.drop_table('item')
    op.drop_table('daily')
    op.drop_table('current_context')
    # ### end Alembic commands ###
