"""add TodoTag hierarchy and TodoTagLink

Revision ID: 8db418bc0eb2
Revises: df035f9234f9
Create Date: 2026-07-05 19:55:54.580953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8db418bc0eb2'
down_revision: Union[str, Sequence[str], None] = 'df035f9234f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['todo_tag.id'], name=op.f('fk_todo_tag_parent_id_todo_tag')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_todo_tag')),
    sa.UniqueConstraint('name', name=op.f('uq_todo_tag_name'))
    )
    op.create_table('todo_tag_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('todo_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['todo_tag.id'], name=op.f('fk_todo_tag_link_tag_id_todo_tag')),
    sa.ForeignKeyConstraint(['todo_id'], ['todo.id'], name=op.f('fk_todo_tag_link_todo_id_todo')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_todo_tag_link'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo_tag_link')
    op.drop_table('todo_tag')
    # ### end Alembic commands ###
