"""add transcript_cache table

Revision ID: 8fe05517ae8d
Revises: 128bbcebe336
Create Date: 2026-09-01 15:02:56.133146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fe05517ae8d'
down_revision: Union[str, Sequence[str], None] = '128bbcebe336'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcript_cache',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('project', sa.String(), nullable=False),
    sa.Column('file_mtime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('session_id', name=op.f('pk_transcript_cache'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transcript_cache')
    # ### end Alembic commands ###
