"""add embedding columns to log_entry

Revision ID: 93124937e750
Revises: 4bb8b89d979d
Create Date: 2026-07-27 02:33:12.666330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93124937e750'
down_revision: Union[str, Sequence[str], None] = '4bb8b89d979d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding_model', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('embedding', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_entry', schema=None) as batch_op:
        batch_op.drop_column('embedding')
        batch_op.drop_column('embedding_model')

    # ### end Alembic commands ###
