"""remove Instruction.system_level column

Revision ID: 93deb240ed0e
Revises: 8fe05517ae8d
Create Date: 2026-09-01 17:48:22.270760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93deb240ed0e'
down_revision: Union[str, Sequence[str], None] = '8fe05517ae8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instruction', schema=None) as batch_op:
        batch_op.drop_column('system_level')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instruction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('system_level', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
