"""add embedding columns to instruction

Revision ID: 96c1da21564b
Revises: e296a6ec8eed
Create Date: 2026-07-27 01:50:09.566544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96c1da21564b'
down_revision: Union[str, Sequence[str], None] = 'e296a6ec8eed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instruction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding_model', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('embedding', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instruction', schema=None) as batch_op:
        batch_op.drop_column('embedding')
        batch_op.drop_column('embedding_model')

    # ### end Alembic commands ###
