"""add Todo.effort

Revision ID: a5cfaa1665af
Revises: 752237ed2641
Create Date: 2026-07-03 00:57:07.521918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5cfaa1665af'
down_revision: Union[str, Sequence[str], None] = '752237ed2641'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('effort', sa.Enum('GRAB', 'RESEARCH', 'PROJECT', name='wishlisteffort', create_constraint=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_column('effort')

    # ### end Alembic commands ###
