"""restructure context as tree, add tags

Revision ID: ab1019a26d33
Revises: a48596724dd0
Create Date: 2026-07-09 21:44:00.397191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab1019a26d33'
down_revision: Union[str, Sequence[str], None] = 'a48596724dd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tag')),
    sa.UniqueConstraint('name', name=op.f('uq_tag_name'))
    )
    op.create_table('context_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('context_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['context_id'], ['context.id'], name=op.f('fk_context_tag_context_id_context')),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name=op.f('fk_context_tag_tag_id_tag')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_context_tag'))
    )
    op.drop_table('todo_tag_link')
    op.drop_table('todo_tag')
    with op.batch_alter_table('context', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_context_parent_id_context'), 'context', ['parent_id'], ['id'])

    with op.batch_alter_table('daily', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_daily_tag_id_tag'), 'tag', ['tag_id'], ['id'])

    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_goal_tag_id_tag'), 'tag', ['tag_id'], ['id'])

    with op.batch_alter_table('idea', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_idea_tag_id_tag'), 'tag', ['tag_id'], ['id'])

    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_todo_tag_id_tag'), 'tag', ['tag_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_todo_tag_id_tag'), type_='foreignkey')
        batch_op.drop_column('tag_id')

    with op.batch_alter_table('idea', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_idea_tag_id_tag'), type_='foreignkey')
        batch_op.drop_column('tag_id')

    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_goal_tag_id_tag'), type_='foreignkey')
        batch_op.drop_column('tag_id')

    with op.batch_alter_table('daily', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_daily_tag_id_tag'), type_='foreignkey')
        batch_op.drop_column('tag_id')

    with op.batch_alter_table('context', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_context_parent_id_context'), type_='foreignkey')
        batch_op.drop_column('parent_id')

    op.create_table('todo_tag',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('parent_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['todo_tag.id'], name=op.f('fk_todo_tag_parent_id_todo_tag')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_todo_tag')),
    sa.UniqueConstraint('name', name=op.f('uq_todo_tag_name'))
    )
    op.create_table('todo_tag_link',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('todo_id', sa.INTEGER(), nullable=False),
    sa.Column('tag_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['todo_tag.id'], name=op.f('fk_todo_tag_link_tag_id_todo_tag')),
    sa.ForeignKeyConstraint(['todo_id'], ['todo.id'], name=op.f('fk_todo_tag_link_todo_id_todo')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_todo_tag_link'))
    )
    op.drop_table('context_tag')
    op.drop_table('tag')
    # ### end Alembic commands ###
