"""add broadcast support to session_message, add session_message_read

Revision ID: ac625a09fecd
Revises: f1cdc140fe60
Create Date: 2026-08-21 18:37:50.123380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac625a09fecd'
down_revision: Union[str, Sequence[str], None] = 'f1cdc140fe60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_message_read',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['session_message.id'], name=op.f('fk_session_message_read_message_id_session_message')),
    sa.ForeignKeyConstraint(['session_id'], ['harness_session.id'], name=op.f('fk_session_message_read_session_id_harness_session')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_message_read')),
    sa.UniqueConstraint('message_id', 'session_id', name='uq_session_message_read')
    )
    with op.batch_alter_table('session_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_broadcast', sa.Boolean(), server_default='0', nullable=False))
        batch_op.alter_column('to_session',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_message', schema=None) as batch_op:
        batch_op.alter_column('to_session',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('is_broadcast')

    op.drop_table('session_message_read')
    # ### end Alembic commands ###
