"""add harness_session and session_message tables

Revision ID: b13920e423df
Revises: c9f948d96d6e
Create Date: 2026-08-16 17:51:14.694678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b13920e423df'
down_revision: Union[str, Sequence[str], None] = 'c9f948d96d6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('harness_session',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cwd', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('INFERRING', 'IDLE', name='harnesssessionstatus', create_constraint=True), nullable=False),
    sa.Column('is_listening', sa.Boolean(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_response_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_harness_session'))
    )
    op.create_table('session_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_session', sa.String(), nullable=False),
    sa.Column('to_session', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_session'], ['harness_session.id'], name=op.f('fk_session_message_from_session_harness_session')),
    sa.ForeignKeyConstraint(['to_session'], ['harness_session.id'], name=op.f('fk_session_message_to_session_harness_session')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_message'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_message')
    op.drop_table('harness_session')
    # ### end Alembic commands ###
