"""add subcommand, duration_ms, args_json to cli_invocation

Revision ID: c424d0c748bc
Revises: 7f62587f429d
Create Date: 2026-08-27 00:06:23.691756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c424d0c748bc'
down_revision: Union[str, Sequence[str], None] = '7f62587f429d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cli_invocation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subcommand', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('duration_ms', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('args_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cli_invocation', schema=None) as batch_op:
        batch_op.drop_column('args_json')
        batch_op.drop_column('duration_ms')
        batch_op.drop_column('subcommand')

    # ### end Alembic commands ###
