"""add kind to todo

Revision ID: cdc697bc3d33
Revises: c424d0c748bc
Create Date: 2026-08-27 03:39:13.232298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdc697bc3d33'
down_revision: Union[str, Sequence[str], None] = 'c424d0c748bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'kind',
                sa.Enum('BUG', 'FEATURE', 'TASK', 'CHORE', name='todokind', create_constraint=True),
                nullable=False,
                server_default='TASK',
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_column('kind')

    # ### end Alembic commands ###
