"""add Daily recurrence and next_due_at

Revision ID: cfa3008307d1
Revises: 62448221d903
Create Date: 2026-07-06 13:04:12.187799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfa3008307d1'
down_revision: Union[str, Sequence[str], None] = '62448221d903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recurrence', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('next_due_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily', schema=None) as batch_op:
        batch_op.drop_column('next_due_at')
        batch_op.drop_column('recurrence')

    # ### end Alembic commands ###
