"""add instruction table

Revision ID: d15c10d5c146
Revises: 80f5d7e6315a
Create Date: 2026-07-16 16:51:49.267799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd15c10d5c146'
down_revision: Union[str, Sequence[str], None] = '80f5d7e6315a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instruction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('trigger', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('context_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['context_id'], ['context.id'], name=op.f('fk_instruction_context_id_context')),
    sa.ForeignKeyConstraint(['parent_id'], ['instruction.id'], name=op.f('fk_instruction_parent_id_instruction')),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name=op.f('fk_instruction_tag_id_tag')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_instruction'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instruction')
    # ### end Alembic commands ###
