"""add entity_link table

Revision ID: d40fc45e46ef
Revises: 0a19ea923200
Create Date: 2026-08-10 20:52:36.762038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd40fc45e46ef'
down_revision: Union[str, Sequence[str], None] = '0a19ea923200'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_a', sa.String(), nullable=False),
    sa.Column('id_a', sa.Integer(), nullable=False),
    sa.Column('type_b', sa.String(), nullable=False),
    sa.Column('id_b', sa.Integer(), nullable=False),
    sa.Column('relation', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_link')),
    sa.UniqueConstraint('type_a', 'id_a', 'type_b', 'id_b', 'relation', name=op.f('uq_entity_link_type_a'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entity_link')
    # ### end Alembic commands ###
