"""add Daily.remind_days_before, drop Daily.reward

Revision ID: dcebc52b1dc9
Revises: 6c6bfdd84138
Create Date: 2026-07-28 22:03:46.077382

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "dcebc52b1dc9"
down_revision: Union[str, Sequence[str], None] = "6c6bfdd84138"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("daily", schema=None) as batch_op:
        batch_op.add_column(sa.Column("remind_days_before", sa.Integer(), nullable=False, server_default="0"))
        batch_op.drop_column("reward")

    with op.batch_alter_table("daily", schema=None) as batch_op:
        batch_op.alter_column("remind_days_before", server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("daily", schema=None) as batch_op:
        batch_op.add_column(sa.Column("reward", sa.TEXT(), nullable=True))
        batch_op.drop_column("remind_days_before")

    # ### end Alembic commands ###
