"""add PgSkill, PgHangout, PgHangoutItem, PgCharacter.hangout_id

Revision ID: df035f9234f9
Revises: 4d58bd25930e
Create Date: 2026-07-05 19:21:10.261402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df035f9234f9'
down_revision: Union[str, Sequence[str], None] = '4d58bd25930e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pg_skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pg_skill')),
    sa.UniqueConstraint('name', name=op.f('uq_pg_skill_name'))
    )
    op.create_table('pg_hangout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('npc_id', sa.Integer(), nullable=False),
    sa.Column('favor', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('skill_xp', sa.Integer(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('is_repeatable', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['npc_id'], ['pg_npc.id'], name=op.f('fk_pg_hangout_npc_id_pg_npc')),
    sa.ForeignKeyConstraint(['skill_id'], ['pg_skill.id'], name=op.f('fk_pg_hangout_skill_id_pg_skill')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pg_hangout')),
    sa.UniqueConstraint('name', name=op.f('uq_pg_hangout_name'))
    )
    op.create_table('pg_hangout_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hangout_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hangout_id'], ['pg_hangout.id'], name=op.f('fk_pg_hangout_item_hangout_id_pg_hangout')),
    sa.ForeignKeyConstraint(['item_id'], ['pg_item.id'], name=op.f('fk_pg_hangout_item_item_id_pg_item')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pg_hangout_item'))
    )
    with op.batch_alter_table('pg_character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hangout_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_pg_character_hangout_id_pg_hangout'), 'pg_hangout', ['hangout_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pg_character', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_pg_character_hangout_id_pg_hangout'), type_='foreignkey')
        batch_op.drop_column('hangout_id')

    op.drop_table('pg_hangout_item')
    op.drop_table('pg_hangout')
    op.drop_table('pg_skill')
    # ### end Alembic commands ###
