"""add embedding columns to goal and todo

Revision ID: e296a6ec8eed
Revises: d15c10d5c146
Create Date: 2026-07-19 19:53:00.997523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e296a6ec8eed'
down_revision: Union[str, Sequence[str], None] = 'd15c10d5c146'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding_model', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('embedding', sa.Text(), nullable=True))

    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding_model', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('embedding', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_column('embedding')
        batch_op.drop_column('embedding_model')

    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.drop_column('embedding')
        batch_op.drop_column('embedding_model')

    # ### end Alembic commands ###
