"""add missing pg_npc_relation.character_id foreign key

The prior column-rename migration's create_foreign_key call didn't take (SQLite's
batch_alter_table recreated the table underneath it) -- this recreates it correctly.

Revision ID: ebdcaff2e117
Revises: 58147824a035
Create Date: 2026-07-05 02:36:41.706661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebdcaff2e117'
down_revision: Union[str, Sequence[str], None] = '58147824a035'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pg_npc_relation', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_pg_npc_relation_character_id_pg_character'), 'pg_character', ['character_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pg_npc_relation', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_pg_npc_relation_character_id_pg_character'), type_='foreignkey')

    # ### end Alembic commands ###
