"""add archivebox host and link push-status columns

Revision ID: f82f6e6c5810
Revises: a1c2e4f7b9d3
Create Date: 2026-08-11 18:32:01.443615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f82f6e6c5810'
down_revision: Union[str, Sequence[str], None] = 'a1c2e4f7b9d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('archived_link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ab_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('push_error', sa.Text(), nullable=True))

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archivebox_host', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('archivebox_host')

    with op.batch_alter_table('archived_link', schema=None) as batch_op:
        batch_op.drop_column('push_error')
        batch_op.drop_column('ab_id')

    # ### end Alembic commands ###
