"""Add usage_sample table for historical usage tracking

Revision ID: fb1c031e54e8
Revises: 93deb240ed0e
Create Date: 2026-09-08 21:43:09.691763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb1c031e54e8'
down_revision: Union[str, Sequence[str], None] = '93deb240ed0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_sample',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sampled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('session_pct', sa.Integer(), nullable=False),
    sa.Column('session_resets_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('week_pct', sa.Integer(), nullable=False),
    sa.Column('week_resets_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage_sample'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usage_sample')
    # ### end Alembic commands ###
