"""add todo blocked_by

Revision ID: fb67de424aa1
Revises: 91777f842fc1
Create Date: 2026-07-01 15:14:06.362485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb67de424aa1'
down_revision: Union[str, Sequence[str], None] = '91777f842fc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('context', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_context_name'), ['name'])

    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blocked_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_todo_blocked_by_id_todo'), 'todo', ['blocked_by_id'], ['id'])

    with op.batch_alter_table('working_memory', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_working_memory_topic'), ['topic'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('working_memory', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_working_memory_topic'), type_='unique')

    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_todo_blocked_by_id_todo'), type_='foreignkey')
        batch_op.drop_column('blocked_by_id')

    with op.batch_alter_table('context', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_context_name'), type_='unique')

    # ### end Alembic commands ###
