"""add pg-specific tables

Revision ID: fbd17e9882cf
Revises: 8c70d52bf981
Create Date: 2026-07-02 00:41:09.574856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbd17e9882cf'
down_revision: Union[str, Sequence[str], None] = '8c70d52bf981'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pg_dungeon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('level_min', sa.Integer(), nullable=True),
    sa.Column('level_max', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pg_dungeon')),
    sa.UniqueConstraint('name', name=op.f('uq_pg_dungeon_name'))
    )
    op.create_table('pg_friendly_player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pg_friendly_player')),
    sa.UniqueConstraint('name', name=op.f('uq_pg_friendly_player_name'))
    )
    op.create_table('pg_npc_race',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pg_npc_race')),
    sa.UniqueConstraint('name', name=op.f('uq_pg_npc_race_name'))
    )
    op.create_table('pg_player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('race', sa.Text(), nullable=False),
    sa.Column('is_druid', sa.Boolean(), nullable=False),
    sa.Column('is_vampire', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pg_player')),
    sa.UniqueConstraint('name', name=op.f('uq_pg_player_name'))
    )
    op.create_table('pg_npc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['race_id'], ['pg_npc_race.id'], name=op.f('fk_pg_npc_race_id_pg_npc_race')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pg_npc')),
    sa.UniqueConstraint('name', name=op.f('uq_pg_npc_name'))
    )
    op.create_table('pg_npc_relation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('npc_id', sa.Integer(), nullable=False),
    sa.Column('favor', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['npc_id'], ['pg_npc.id'], name=op.f('fk_pg_npc_relation_npc_id_pg_npc')),
    sa.ForeignKeyConstraint(['player_id'], ['pg_player.id'], name=op.f('fk_pg_npc_relation_player_id_pg_player')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pg_npc_relation'))
    )
    op.create_table('pg_quest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('giver_npc_id', sa.Integer(), nullable=False),
    sa.Column('completion_npc_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('objectives', sa.Text(), nullable=True),
    sa.Column('rewards', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['completion_npc_id'], ['pg_npc.id'], name=op.f('fk_pg_quest_completion_npc_id_pg_npc')),
    sa.ForeignKeyConstraint(['giver_npc_id'], ['pg_npc.id'], name=op.f('fk_pg_quest_giver_npc_id_pg_npc')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pg_quest'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pg_quest')
    op.drop_table('pg_npc_relation')
    op.drop_table('pg_npc')
    op.drop_table('pg_player')
    op.drop_table('pg_npc_race')
    op.drop_table('pg_friendly_player')
    op.drop_table('pg_dungeon')
    # ### end Alembic commands ###
