"""add IrlItem

Revision ID: feab15549d43
Revises: 9bfa419a127c
Create Date: 2026-07-03 13:56:50.587249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feab15549d43'
down_revision: Union[str, Sequence[str], None] = '9bfa419a127c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('irl_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['item.id'], name=op.f('fk_irl_item_id_item')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_irl_item'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('irl_item')
    # ### end Alembic commands ###
