#!/usr/bin/env python3
"""Mark one or more Todos as done. Usage: complete.py ID [ID ...]"""
import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from models import Todo, TodoStatus, sess

parser = argparse.ArgumentParser(description="Mark Todos as done")
parser.add_argument("ids", nargs="+", type=int, help="Todo id(s) to mark done")
args = parser.parse_args()

for todo_id in args.ids:
    todo = sess.get(Todo, todo_id)
    if todo is None:
        print(f"Todo #{todo_id}: not found", file=sys.stderr)
        continue
    todo.status = TodoStatus.DONE
    print(f"Todo #{todo_id}: {todo.title!r} -> done")

sess.commit()
